# Generated by Django 4.2.16 on 2026-08-11 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Meta Holandês — Embrapa', max_length=200, verbose_name='Nome da curva')),
                ('raca', models.CharField(choices=[('holandes', 'Holandês'), ('jersey', 'Jersey'), ('girolando', 'Girolando'), ('gir_leiteiro', 'Gir Leiteiro'), ('guzera', 'Guzerá'), ('pardo_suico', 'Pardo Suíço'), ('mestaca', 'Mestiça'), ('todas', 'Todas as raças')], max_length=30, verbose_name='Raça')),
                ('fonte', models.CharField(blank=True, help_text='Ex: Embrapa, Protocolo interno, NRC 2001', max_length=200, verbose_name='Fonte')),
                ('vigencia_inicio', models.DateField(verbose_name='Vigência inicial')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência final')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_desenvolvimento', to='core.propriedade')),
            ],
            options={
                'verbose_name': 'Meta de desenvolvimento',
                'verbose_name_plural': 'Metas de desenvolvimento',
            },
        ),
        migrations.CreateModel(
            name='ReferencialTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(choices=[('dias_secos', 'Dias secos'), ('dias_pre_parto', 'Dias no pré-parto'), ('tempo_colostragem', 'Tempo até primeira colostragem (h)'), ('volume_colostro', 'Volume de colostro (ml/kg PV)'), ('brix_colostro', 'Brix do colostro (%)'), ('gmd_aleitamento', 'GMD no aleitamento (kg/dia)'), ('gmd_recria', 'GMD na recria (kg/dia)'), ('peso_60d', 'Peso aos 60 dias (kg)'), ('peso_180d', 'Peso aos 180 dias (kg)'), ('idade_desaleitamento', 'Idade ao desaleitamento (dias)'), ('mortalidade_60d', 'Mortalidade até 60 dias (%)'), ('incidencia_diarreia', 'Incidência de diarreia (%)'), ('incidencia_pneumonia', 'Incidência de pneumonia (%)'), ('outro', 'Outro')], max_length=50, verbose_name='Indicador')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do indicador')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Valor mínimo')),
                ('valor_ideal', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Valor ideal/recomendado')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Valor máximo')),
                ('unidade', models.CharField(max_length=50, verbose_name='Unidade')),
                ('populacao', models.CharField(max_length=200, verbose_name='População à qual se aplica')),
                ('fonte', models.CharField(max_length=200, verbose_name='Fonte')),
                ('autor', models.CharField(blank=True, max_length=300, verbose_name='Autor(es)')),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações e limitações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referencial técnico',
                'verbose_name_plural': 'Referenciais técnicos',
                'ordering': ['indicador', '-ano'],
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('colostragem', 'Colostragem'), ('umbigo', 'Cura de umbigo'), ('alimentacao', 'Alimentação'), ('vacinacao', 'Vacinação'), ('desaleitamento', 'Desaleitamento'), ('pre_parto', 'Pré-parto'), ('sanitario', 'Sanitário / Tratamentos'), ('reproducao', 'Reprodução'), ('geral', 'Geral')], max_length=30, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('versao', models.PositiveSmallIntegerField(default=1, verbose_name='Versão')),
                ('vigencia_inicio', models.DateField(verbose_name='Vigência inicial')),
                ('vigencia_fim', models.DateField(blank=True, help_text='Deixe em branco para protocolo vigente', null=True, verbose_name='Vigência final')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='core.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['nome', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='MetaReprodutiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('raca', models.CharField(choices=[('holandes', 'Holandês'), ('jersey', 'Jersey'), ('girolando', 'Girolando'), ('gir_leiteiro', 'Gir Leiteiro'), ('guzera', 'Guzerá'), ('pardo_suico', 'Pardo Suíço'), ('mestaca', 'Mestiça'), ('todas', 'Todas as raças')], max_length=30, verbose_name='Raça')),
                ('peso_adulto_medio_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Peso adulto médio do rebanho (kg)')),
                ('percentual_peso_adulto', models.DecimalField(decimal_places=1, default=55.0, help_text='Embrapa recomenda 50–55%', max_digits=4, verbose_name='Percentual do peso adulto (%)')),
                ('peso_minimo_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Referência: Holandês 330–340kg, Jersey 230–240kg', max_digits=6, null=True, verbose_name='Peso mínimo para IA (kg)')),
                ('ecc_minimo', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='ECC mínimo')),
                ('idade_minima_meses', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Idade mínima (meses)')),
                ('idade_alvo_meses', models.PositiveSmallIntegerField(default=13, verbose_name='Idade alvo para primeira IA (meses)')),
                ('gmd_minimo_recria', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='GMD mínimo na recria (kg/dia)')),
                ('vigencia_inicio', models.DateField(verbose_name='Vigência inicial')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência final')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_reprodutivas', to='core.propriedade')),
            ],
            options={
                'verbose_name': 'Meta reprodutiva',
                'verbose_name_plural': 'Metas reprodutivas',
            },
        ),
        migrations.CreateModel(
            name='PontoMetaDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peso', 'Peso (kg)'), ('altura', 'Altura na garupa (cm)'), ('perimetro', 'Perímetro torácico (cm)')], default='peso', max_length=20, verbose_name='Tipo de medida')),
                ('idade_dias', models.PositiveSmallIntegerField(verbose_name='Idade (dias)')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor mínimo')),
                ('valor_ideal', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor ideal')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor máximo')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='config_tecnica.metadesenvolvimento', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Ponto de meta',
                'verbose_name_plural': 'Pontos de meta',
                'ordering': ['meta', 'tipo', 'idade_dias'],
                'unique_together': {('meta', 'tipo', 'idade_dias')},
            },
        ),
    ]
