# Generated by Django 4.2.16 on 2026-08-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('config_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('colostragem_tempo', 'Colostragem — tempo até 1ª mamada (horas)'), ('colostragem_volume_relativo', 'Colostragem — volume relativo ao peso (% PV)'), ('colostragem_brix', 'Colostragem — qualidade Brix (%)'), ('umbigo_tempo', 'Umbigo — tempo até 1ª cura (horas)'), ('dias_secos_minimo', 'Dias secos — mínimo'), ('dias_secos_maximo', 'Dias secos — máximo'), ('dias_pre_parto_minimo', 'Pré-parto — dias mínimos no lote'), ('peso_por_idade', 'Crescimento — peso mínimo por idade'), ('desaleitamento_idade_minima', 'Desaleitamento — idade mínima (dias)'), ('desaleitamento_idade_maxima', 'Desaleitamento — idade máxima (dias)'), ('desaleitamento_peso_minimo', 'Desaleitamento — peso mínimo (kg)'), ('ia_peso_minimo', 'IA — peso mínimo na cobertura (kg)')], max_length=50, verbose_name='Código do critério')),
                ('descricao_custom', models.CharField(blank=True, help_text='Deixe em branco para usar a descrição padrão', max_length=200, verbose_name='Descrição personalizada')),
                ('valor_limite', models.DecimalField(decimal_places=3, help_text='Valor numérico do critério (ex: 2 para "até 2 horas")', max_digits=8, verbose_name='Valor limite')),
                ('unidade', models.CharField(max_length=30, verbose_name='Unidade')),
                ('escopo_raca', models.CharField(choices=[('holandes', 'Holandês'), ('jersey', 'Jersey'), ('girolando', 'Girolando'), ('gir_leiteiro', 'Gir Leiteiro'), ('guzera', 'Guzerá'), ('pardo_suico', 'Pardo Suíço'), ('mestaca', 'Mestiça'), ('todas', 'Todas as raças')], default='todas', help_text='Aplicar apenas a esta raça, ou Todas', max_length=30, verbose_name='Escopo — raça')),
                ('vigencia_inicio', models.DateField(verbose_name='Vigência inicial')),
                ('vigencia_fim', models.DateField(blank=True, help_text='Deixe em branco para critério vigente', null=True, verbose_name='Vigência final')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_conformidade', to='core.propriedade', verbose_name='Propriedade')),
                ('referencial_base', models.ForeignKey(blank=True, help_text='Referência bibliográfica que embasou este critério (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_tecnica.referencialtecnico', verbose_name='Referencial técnico base')),
            ],
            options={
                'verbose_name': 'Critério de conformidade',
                'verbose_name_plural': 'Critérios de conformidade',
                'ordering': ['codigo'],
            },
        ),
    ]
