# Generated by Django 4.2.16 on 2026-08-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curaumbigo',
            name='comprimento_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Medida do coto que ainda não caiu', null=True, verbose_name='Comprimento do coto (mm)'),
        ),
        migrations.AddField(
            model_name='curaumbigo',
            name='cor_umbigo',
            field=models.CharField(blank=True, help_text='Ex: rosa, vermelho, roxo, preto', max_length=20, null=True, verbose_name='Cor do umbigo'),
        ),
        migrations.AddField(
            model_name='curaumbigo',
            name='espessura_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Medida na base do cordão umbilical', null=True, verbose_name='Espessura do cordão (mm)'),
        ),
        migrations.AddField(
            model_name='ocorrenciasanitaria',
            name='apetite_score',
            field=models.IntegerField(blank=True, help_text='0=Normal/Voraz, 1=Reduzido, 2=Ausente', null=True, verbose_name='Score de apetite (0-2)'),
        ),
        migrations.AddField(
            model_name='ocorrenciasanitaria',
            name='desidratacao_grau',
            field=models.IntegerField(blank=True, help_text='0-15%: 0=Sem desidratação, 5-8%=Leve, 8-12%=Moderada, >12%=Severa', null=True, verbose_name='Grau de desidratação (%)'),
        ),
        migrations.AddField(
            model_name='ocorrenciasanitaria',
            name='escore_fezes',
            field=models.IntegerField(blank=True, help_text='0=Normal, 1=Ligeiramente amolecidas, 2=Amolecidas, 3=Líquidas', null=True, verbose_name='Escore de fezes (0-3)'),
        ),
    ]
