# Generated by Django 4.2.16 on 2026-08-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_fase2_campos_bea_opcionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='curaumbigo',
            name='dias_queda_cordao',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de dias desde o nascimento até a queda do cordão', null=True, verbose_name='Dias para queda do cordão umbilical'),
        ),
        migrations.AddField(
            model_name='curaumbigo',
            name='numero_infeccoes',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Contador de episódios de onfalite neste animal', null=True, verbose_name='Número de infecções umbilicais'),
        ),
        migrations.AddField(
            model_name='curaumbigo',
            name='uso_antibiotico_bea',
            field=models.BooleanField(blank=True, help_text='Se houve uso de antibiótico relacionado ao manejo umbilical', null=True, verbose_name='Uso de antibiótico (protocolo BEA)?'),
        ),
        migrations.AddField(
            model_name='ocorrenciasanitaria',
            name='faixa_etaria_bea',
            field=models.CharField(blank=True, help_text='Ex: 0-7d, 8-15d, 16-30d, 31-60d', max_length=20, null=True, verbose_name='Faixa etária BEA'),
        ),
        migrations.AddField(
            model_name='ocorrenciasanitaria',
            name='ultrassom_7dias',
            field=models.BooleanField(blank=True, help_text='Para avaliação de transferência de imunidade passiva', null=True, verbose_name='Ultrassom realizado nos primeiros 7 dias?'),
        ),
        migrations.AlterField(
            model_name='curaumbigo',
            name='comprimento_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CAMPO EXTRA: Medida do coto que ainda não caiu', null=True, verbose_name='Comprimento do coto (mm) - EXTRA'),
        ),
        migrations.AlterField(
            model_name='curaumbigo',
            name='cor_umbigo',
            field=models.CharField(blank=True, help_text='CAMPO EXTRA: Ex: rosa, vermelho, roxo, preto', max_length=20, null=True, verbose_name='Cor do umbigo - EXTRA'),
        ),
        migrations.AlterField(
            model_name='curaumbigo',
            name='espessura_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CAMPO EXTRA: Medida na base do cordão umbilical', null=True, verbose_name='Espessura do cordão (mm) - EXTRA'),
        ),
        migrations.AlterField(
            model_name='ocorrenciasanitaria',
            name='apetite_score',
            field=models.IntegerField(blank=True, help_text='CAMPO EXTRA: 0=Normal/Voraz, 1=Reduzido, 2=Ausente', null=True, verbose_name='Score de apetite (0-2) - EXTRA'),
        ),
        migrations.AlterField(
            model_name='ocorrenciasanitaria',
            name='desidratacao_grau',
            field=models.IntegerField(blank=True, help_text='CAMPO EXTRA: 0-15%: 0=Sem desidratação, 5-8%=Leve, 8-12%=Moderada, >12%=Severa', null=True, verbose_name='Grau de desidratação (%) - EXTRA'),
        ),
    ]
