# Generated by Django 4.2.16 on 2026-08-31 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_fase2b_campos_faltantes_spec_aprovada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesagemBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brix_serico', models.DecimalField(blank=True, decimal_places=1, help_text='Medição do Brix no sangue para avaliação de imunidade', max_digits=4, null=True, verbose_name='Brix sérico (%)')),
                ('data_coleta_sangue', models.DateField(blank=True, help_text='Data em que foi coletado o sangue para análise de Brix', null=True, verbose_name='Data da coleta de sangue')),
                ('resultado_tip', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('adequado', 'Adequado'), ('falha', 'Falha')], help_text='Resultado da avaliação de transferência de imunidade passiva', max_length=20, verbose_name='Resultado TIP')),
                ('pesagem_origem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extensao_bea', to='eventos.pesagem', verbose_name='Pesagem')),
            ],
            options={
                'verbose_name': 'Extensão BEA - Pesagem',
                'verbose_name_plural': 'Extensões BEA - Pesagem',
            },
        ),
        migrations.CreateModel(
            name='ColostragemBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_primeira_mamada', models.DateTimeField(blank=True, help_text='Registro do primeiro fornecimento de colostro', null=True, verbose_name='Horário da primeira mamada')),
                ('horario_segunda_mamada', models.DateTimeField(blank=True, help_text='Registro do segundo fornecimento de colostro', null=True, verbose_name='Horário da segunda mamada')),
                ('metodo_descongelamento', models.CharField(blank=True, choices=[('banho_maria', 'Banho-maria'), ('ambiente', 'Temperatura ambiente')], help_text='Como o colostro foi descongelado (se aplicável)', max_length=20, verbose_name='Método de descongelamento')),
                ('leite_transicao', models.BooleanField(blank=True, help_text='Se houve fornecimento de leite de transição', null=True, verbose_name='Leite de transição oferecido?')),
                ('colostragem_origem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extensao_bea', to='eventos.colostragem', verbose_name='Colostragem')),
            ],
            options={
                'verbose_name': 'Extensão BEA - Colostragem',
                'verbose_name_plural': 'Extensões BEA - Colostragem',
            },
        ),
    ]
