# Generated by Django 4.2.16 on 2026-09-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_fase3_extensoes_bea_onetoone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curaumbigo',
            name='uso_antibiotico_bea',
        ),
        migrations.RemoveField(
            model_name='ocorrenciasanitaria',
            name='faixa_etaria_bea',
        ),
        migrations.RemoveField(
            model_name='protocoloalimentar',
            name='fornecimentos_dia',
        ),
        migrations.RemoveField(
            model_name='protocoloalimentar',
            name='volume_dia_litros',
        ),
        migrations.AddField(
            model_name='colostragem',
            name='leite_transicao',
            field=models.BooleanField(blank=True, help_text='Se houve fornecimento de leite de transição após colostro', null=True, verbose_name='Leite de transição oferecido?'),
        ),
        migrations.AddField(
            model_name='colostragem',
            name='metodo_descongelamento',
            field=models.CharField(blank=True, choices=[('banho_maria', 'Banho-maria'), ('ambiente', 'Temperatura ambiente')], help_text='Como o colostro congelado foi descongelado', max_length=20, verbose_name='Método de descongelamento'),
        ),
        migrations.AddField(
            model_name='colostragem',
            name='volume_segunda_mamada_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Volume fornecido na segunda mamada (meta: +5% peso até 12h)', null=True, verbose_name='Volume segunda mamada (ml)'),
        ),
        migrations.AddField(
            model_name='curaumbigo',
            name='antibiotico_usado',
            field=models.BooleanField(blank=True, help_text='Se houve necessidade de antibiótico sistêmico por onfalite', null=True, verbose_name='Antibiótico sistêmico usado?'),
        ),
        migrations.AddField(
            model_name='curaumbigo',
            name='escore_infeccao',
            field=models.IntegerField(blank=True, choices=[(0, '0 — Normal/sem infecção'), (1, '1 — Infecção leve'), (2, '2 — Infecção moderada/grave')], help_text='0=Normal, 1=Infecção leve, 2=Moderada/Grave', null=True, verbose_name='Escore de infecção umbilical'),
        ),
        migrations.AddField(
            model_name='curaumbigo',
            name='uso_preventivo',
            field=models.BooleanField(blank=True, help_text='Se houve aplicação preventiva de medicação injetável', null=True, verbose_name='Uso preventivo de injetáveis?'),
        ),
        migrations.AddField(
            model_name='desaleitamento',
            name='consumo_concentrado_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Meta ao desmame: 1,2-1,5 kg/dia', max_digits=5, null=True, verbose_name='Consumo concentrado exato (kg/dia)'),
        ),
        migrations.AddField(
            model_name='desaleitamento',
            name='duracao_gradual_dias',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Meta: ≥10 dias para desaleitamento gradual', null=True, verbose_name='Duração desaleitamento gradual (dias)'),
        ),
        migrations.AddField(
            model_name='ocorrenciasanitaria',
            name='brix_serico_tip',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Medição do Brix no sangue (≥9,4%=excelente, <8,1%=falha)', max_digits=4, null=True, verbose_name='Brix sérico/TIP (%)'),
        ),
        migrations.AddField(
            model_name='ocorrenciasanitaria',
            name='escore_respiratorio',
            field=models.IntegerField(blank=True, choices=[(0, '0 — Normal'), (1, '1 — Alteração leve'), (2, '2 — Alteração moderada'), (3, '3 — Alteração grave')], help_text='0=Normal, 1-3=Alterado', null=True, verbose_name='Escore respiratório'),
        ),
        migrations.AddField(
            model_name='ocorrenciasanitaria',
            name='faixa_etaria_auto',
            field=models.CharField(blank=True, choices=[('0-30d', '0-30 dias'), ('31-60d', '31-60 dias'), ('>60d', 'Acima de 60 dias')], help_text='Calculada automaticamente pela idade no registro', max_length=10, verbose_name='Faixa etária (automática)'),
        ),
        migrations.AddField(
            model_name='protocoloalimentar',
            name='consumo_concentrado_estimado_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Consumo estimado concentrado (kg/dia)'),
        ),
        migrations.AddField(
            model_name='protocoloalimentar',
            name='correcao_solidos',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_aplicavel', 'Não aplicável')], help_text='Se há adição de solúveis para elevar sólidos totais', max_length=20, verbose_name='Correção de sólidos'),
        ),
        migrations.AddField(
            model_name='protocoloalimentar',
            name='frequencia_mamadas',
            field=models.CharField(blank=True, choices=[('1x', '1x ao dia'), ('2x', '2x ao dia'), ('3x', '3x ao dia'), ('a_vontade', 'À vontade')], max_length=20, verbose_name='Frequência de mamadas'),
        ),
        migrations.AddField(
            model_name='protocoloalimentar',
            name='tipo_leite_detalhado',
            field=models.CharField(blank=True, help_text='Ex: Leite integral pasteurizado, sucedâneo 22% PB', max_length=100, verbose_name='Tipo de leite detalhado'),
        ),
        migrations.AddField(
            model_name='protocoloalimentar',
            name='tipo_volumoso',
            field=models.CharField(blank=True, help_text='Ex: Feno coast-cross, silagem milho', max_length=100, verbose_name='Tipo de volumoso'),
        ),
        migrations.AddField(
            model_name='protocoloalimentar',
            name='volume_dia_0_30_litros',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Meta grande porte: ≥7L/dia', max_digits=4, null=True, verbose_name='Volume diário 0-30 dias (L)'),
        ),
        migrations.AddField(
            model_name='protocoloalimentar',
            name='volume_dia_31_60_litros',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Volume diário 31-60 dias (L)'),
        ),
        migrations.AddField(
            model_name='protocoloalimentar',
            name='volume_dia_acima_60_litros',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Volume diário acima 60 dias (L)'),
        ),
        migrations.AlterField(
            model_name='curaumbigo',
            name='dias_queda_cordao',
            field=models.CharField(blank=True, choices=[('3-4', '3-4 dias'), ('5-7', '5-7 dias'), ('>8', 'Mais de 8 dias')], help_text='Tempo desde nascimento até queda completa do cordão', max_length=10, null=True, verbose_name='Dias para queda do cordão'),
        ),
        migrations.AlterField(
            model_name='ocorrenciasanitaria',
            name='escore_fezes',
            field=models.IntegerField(blank=True, choices=[(0, '0 — Normais/firmes'), (1, '1 — Ligeiramente amolecidas'), (2, '2 — Amolecidas/pastosas'), (3, '3 — Líquidas/aquosas')], help_text='0-1=Normal, 2-3=Diarreia', null=True, verbose_name='Escore de fezes'),
        ),
        migrations.AlterField(
            model_name='ocorrenciasanitaria',
            name='temperatura_retal',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Referência doença respiratória: ≥39,4°C', max_digits=4, null=True, verbose_name='Temperatura retal (°C)'),
        ),
    ]
