# Generated by Django 4.2.16 on 2026-08-11 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjecaoReprodutiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calculo', models.DateField(verbose_name='Data do cálculo')),
                ('peso_atual_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso atual (kg)')),
                ('peso_alvo_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso alvo (kg)')),
                ('gmd_projetado', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='GMD projetado (kg/dia)')),
                ('dias_ate_peso_alvo', models.IntegerField(blank=True, null=True, verbose_name='Dias até o peso alvo')),
                ('data_estimada', models.DateField(blank=True, null=True, verbose_name='Data estimada para IA')),
                ('idade_estimada_meses', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Idade estimada (meses)')),
                ('status_trajetoria', models.CharField(choices=[('favoravel', 'Favorável'), ('atencao', 'Atenção'), ('desfavoravel', 'Desfavorável'), ('insuficiente', 'Dados insuficientes')], max_length=20, verbose_name='Trajetória')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('meta_reprodutiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_tecnica.metareprodutiva', verbose_name='Meta reprodutiva usada')),
                ('terneira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecoes_reprodutivas', to='animais.animal', verbose_name='Terneira')),
            ],
            options={
                'verbose_name': 'Projeção reprodutiva',
                'verbose_name_plural': 'Projeções reprodutivas',
                'ordering': ['-data_calculo'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Geralmente a data de nascimento', verbose_name='Data de início')),
                ('duracao_dias', models.PositiveSmallIntegerField(default=180, verbose_name='Duração (dias)')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('terneira', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programa_acompanhamento', to='animais.animal', verbose_name='Terneira')),
            ],
            options={
                'verbose_name': 'Programa de acompanhamento',
                'verbose_name_plural': 'Programas de acompanhamento',
            },
        ),
        migrations.CreateModel(
            name='CoberturaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('iatf', 'IATF'), ('ia_tempo_fixo', 'IA em tempo fixo'), ('ia_cio', 'IA no cio'), ('monta_natural', 'Monta natural')], max_length=20, verbose_name='Tipo')),
                ('touro_semen', models.CharField(blank=True, max_length=200, verbose_name='Touro/Sêmen')),
                ('peso_na_ia_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso na IA (kg)')),
                ('ecc_na_ia', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='ECC na IA')),
                ('numero_servico', models.PositiveSmallIntegerField(default=1, verbose_name='Número do serviço')),
                ('resultado', models.CharField(choices=[('prenhe', 'Prenhe'), ('vazia', 'Vazia'), ('aguardando', 'Aguardando diagnóstico')], default='aguardando', max_length=20, verbose_name='Resultado')),
                ('data_diagnostico', models.DateField(blank=True, null=True, verbose_name='Data do diagnóstico')),
                ('data_prevista_parto', models.DateField(blank=True, null=True, verbose_name='Data prevista do parto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('terneira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas_ia', to='animais.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Cobertura / IA',
                'verbose_name_plural': 'Coberturas / IA',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointSesMeses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(verbose_name='Data da avaliação')),
                ('idade_dias', models.PositiveSmallIntegerField(verbose_name='Idade na avaliação (dias)')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('peso_meta_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso meta (kg)')),
                ('percentual_meta', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='% da meta atingida')),
                ('gmd_total', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='GMD total (kg/dia)')),
                ('gmd_30_dias', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='GMD últimos 30d (kg/dia)')),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('perimetro_toracico_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Perímetro torácico (cm)')),
                ('ecc', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='ECC')),
                ('diarreia_ocorrencias', models.PositiveSmallIntegerField(default=0, verbose_name='Episódios de diarreia')),
                ('pneumonia_ocorrencias', models.PositiveSmallIntegerField(default=0, verbose_name='Episódios de pneumonia')),
                ('onfalite_ocorrencias', models.PositiveSmallIntegerField(default=0, verbose_name='Episódios de onfalite')),
                ('total_tratamentos', models.PositiveSmallIntegerField(default=0, verbose_name='Total de tratamentos')),
                ('doenca_ativa', models.BooleanField(default=False, verbose_name='Doença ativa?')),
                ('desaleitada', models.BooleanField(default=False, verbose_name='Desaleitada?')),
                ('consumo_concentrado_adequado', models.BooleanField(blank=True, null=True, verbose_name='Consumo de concentrado adequado?')),
                ('status_checkpoint', models.CharField(choices=[('adequado', 'Adequado'), ('atencao', 'Atenção'), ('critico', 'Crítico'), ('pendente', 'Pendente de avaliação')], default='pendente', max_length=20, verbose_name='Status')),
                ('crescimento_estrutural', models.CharField(blank=True, choices=[('adequado', 'Adequado'), ('atencao', 'Atenção'), ('insuficiente', 'Insuficiente')], max_length=20, verbose_name='Crescimento estrutural')),
                ('status_trajetoria', models.CharField(choices=[('favoravel', 'Favorável'), ('atencao', 'Atenção'), ('desfavoravel', 'Desfavorável'), ('insuficiente', 'Dados insuficientes')], default='insuficiente', max_length=20, verbose_name='Trajetória')),
                ('indicadores_trajetoria', models.TextField(blank=True, verbose_name='Indicadores que fundamentam a trajetória')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações técnicas')),
                ('recomendacoes', models.TextField(blank=True, verbose_name='Recomendações de manejo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('programa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint', to='programas.programaacompanhamento', verbose_name='Programa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Checkpoint de 6 meses',
                'verbose_name_plural': 'Checkpoints de 6 meses',
            },
        ),
    ]
