# Generated by Django 4.2.16 on 2026-08-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da propriedade')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Município')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=200, verbose_name='Responsável técnico')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Contato')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['nome'],
            },
        ),
    ]
