# Generated by Django 4.2.16 on 2026-08-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_tecnica', '0002_criterioconformidade'),
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField(verbose_name='Data do evento')),
                ('evento_tipo', models.CharField(help_text='Nome do model avaliado: Parto, Colostragem, CuraUmbigo, Pesagem, Desaleitamento', max_length=50, verbose_name='Tipo do evento')),
                ('evento_id', models.PositiveIntegerField(verbose_name='ID do evento')),
                ('valor_observado', models.DecimalField(blank=True, decimal_places=3, help_text='Null quando resultado = dado_ausente', max_digits=10, null=True, verbose_name='Valor observado')),
                ('valor_referencia', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Valor de referência (limite)')),
                ('desvio', models.DecimalField(blank=True, decimal_places=3, help_text='Positivo = acima do limite, negativo = abaixo', max_digits=10, null=True, verbose_name='Desvio (observado − referência)')),
                ('resultado', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não conforme'), ('dado_ausente', 'Dado ausente'), ('nao_aplicavel', 'Não aplicável')], max_length=20, verbose_name='Resultado')),
                ('motivo_ausencia', models.CharField(blank=True, help_text='Explica por que o dado não estava disponível', max_length=200, verbose_name='Motivo do dado ausente')),
                ('calculado_em', models.DateTimeField(auto_now_add=True, verbose_name='Calculado em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_conformidade', to='animais.animal', verbose_name='Animal')),
                ('criterio', models.ForeignKey(blank=True, help_text='Null apenas para conformidade de peso_por_idade (usa MetaDesenvolvimento)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='config_tecnica.criterioconformidade', verbose_name='Critério')),
                ('meta_desenvolvimento', models.ForeignKey(blank=True, help_text='Usado apenas para conformidade de peso por idade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_tecnica.metadesenvolvimento', verbose_name='Meta de desenvolvimento')),
            ],
            options={
                'verbose_name': 'Resultado de conformidade',
                'verbose_name_plural': 'Resultados de conformidade',
                'ordering': ['-data_evento', 'animal'],
                'indexes': [models.Index(fields=['animal', 'data_evento'], name='indicadores_animal__90ade1_idx'), models.Index(fields=['criterio', 'resultado'], name='indicadores_criteri_ffa5dc_idx'), models.Index(fields=['evento_tipo', 'evento_id'], name='indicadores_evento__193f06_idx')],
            },
        ),
    ]
