# Generated by Django 4.2.16 on 2026-08-11 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50, verbose_name='Identificação (brinco/chip/nome)')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], max_length=1, verbose_name='Sexo')),
                ('raca', models.CharField(choices=[('holandes', 'Holandês'), ('jersey', 'Jersey'), ('girolando', 'Girolando'), ('gir_leiteiro', 'Gir Leiteiro'), ('guzera', 'Guzerá'), ('pardo_suico', 'Pardo Suíço'), ('mestaca', 'Mestiça'), ('outra', 'Outra')], max_length=30, verbose_name='Raça')),
                ('raca_descricao', models.CharField(blank=True, help_text='Detalhe quando raça = Mestiça ou Outra', max_length=100, verbose_name='Descrição da raça')),
                ('categoria', models.CharField(choices=[('terneira', 'Terneira'), ('novilha', 'Novilha'), ('vaca', 'Vaca'), ('touro', 'Touro'), ('bezerro', 'Bezerro (macho)')], max_length=20, verbose_name='Categoria')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('pai_identificacao', models.CharField(blank=True, help_text='Touro ou sêmen utilizado', max_length=100, verbose_name='Identificação do pai')),
                ('situacao', models.CharField(choices=[('ativa', 'Ativa'), ('morta', 'Morta'), ('vendida', 'Vendida'), ('descartada', 'Descartada'), ('transferida', 'Transferida')], default='ativa', max_length=20, verbose_name='Situação')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('motivo_saida', models.TextField(blank=True, verbose_name='Motivo da saída')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='animais.animal', verbose_name='Mãe')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='core.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['identificacao'],
                'unique_together': {('propriedade', 'identificacao')},
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do lote')),
                ('tipo', models.CharField(choices=[('pre_parto', 'Pré-parto'), ('maternidade', 'Maternidade'), ('aleitamento', 'Aleitamento'), ('pos_desaleitamento', 'Pós-desaleitamento'), ('recria', 'Recria'), ('vacas', 'Vacas em lactação'), ('secas', 'Vacas secas'), ('geral', 'Geral')], max_length=30, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['nome'],
                'unique_together': {('propriedade', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da movimentação')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='animais.animal', verbose_name='Animal')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='animais.lote', verbose_name='Lote')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimentação de lote',
                'verbose_name_plural': 'Movimentações de lote',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='CicloReprodutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lactacao', models.PositiveSmallIntegerField(blank=True, help_text='1 = primeira cria, 2 = segunda, etc.', null=True, verbose_name='Número da lactação')),
                ('data_cobertura', models.DateField(blank=True, null=True, verbose_name='Data da cobertura/IA')),
                ('touro_semen', models.CharField(blank=True, max_length=200, verbose_name='Touro/Sêmen utilizado')),
                ('data_previsao_parto', models.DateField(blank=True, null=True, verbose_name='Previsão do parto')),
                ('data_secagem', models.DateField(blank=True, null=True, verbose_name='Data da secagem')),
                ('tratamento_secagem', models.CharField(blank=True, help_text='Ex: secagem seletiva, vaca seca total, produto utilizado', max_length=200, verbose_name='Tratamento de secagem')),
                ('data_entrada_pre_parto', models.DateField(blank=True, null=True, verbose_name='Entrada no pré-parto')),
                ('ecc_entrada_pre_parto', models.DecimalField(blank=True, decimal_places=1, help_text='Escore de Condição Corporal (1,0 a 5,0)', max_digits=3, null=True, verbose_name='ECC na entrada do pré-parto')),
                ('situacao', models.CharField(choices=[('gestando', 'Gestando'), ('encerrado_parto', 'Encerrado — Parto realizado'), ('encerrado_aborto', 'Encerrado — Aborto'), ('encerrado_outro', 'Encerrado — Outro motivo')], default='gestando', max_length=30, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote_pre_parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animais.lote', verbose_name='Lote pré-parto')),
                ('vaca', models.ForeignKey(limit_choices_to={'sexo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_reprodutivos', to='animais.animal', verbose_name='Vaca')),
            ],
            options={
                'verbose_name': 'Ciclo reprodutivo',
                'verbose_name_plural': 'Ciclos reprodutivos',
                'ordering': ['-data_previsao_parto'],
            },
        ),
    ]
