# Generated by Django 4.2.16 on 2026-08-31 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComportamentoBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('estimulo_6h', models.BooleanField(blank=True, help_text='Estímulo tátil aplicado nas primeiras 6 horas de vida', null=True, verbose_name='Estímulo tátil nas primeiras 6h?')),
                ('continuidade_diaria', models.BooleanField(blank=True, help_text='Estímulo tátil mantido diariamente após as primeiras 6h', null=True, verbose_name='Continuidade diária do estímulo?')),
                ('idade_agrupamento_dias', models.PositiveIntegerField(blank=True, help_text='Idade em que a terneira foi colocada com outras', null=True, verbose_name='Idade do agrupamento (dias)')),
                ('tipo_agrupamento', models.CharField(blank=True, choices=[('pares', 'Em pares'), ('grupos', 'Em grupos'), ('individual', 'Mantida individual')], max_length=20, verbose_name='Tipo de agrupamento')),
                ('tem_enriquecimento', models.BooleanField(blank=True, null=True, verbose_name='Tem enriquecimento ambiental?')),
                ('tipo_enriquecimento', models.CharField(blank=True, help_text='Descreva os itens de enriquecimento ambiental', max_length=200, verbose_name='Tipo de enriquecimento')),
                ('mocacao_realizada', models.BooleanField(blank=True, null=True, verbose_name='Mochação realizada?')),
                ('mocacao_idade_semanas', models.PositiveIntegerField(blank=True, help_text='Meta: 3-4 semanas', null=True, verbose_name='Idade na mochação (semanas)')),
                ('mocacao_metodo', models.CharField(blank=True, choices=[('ferro_quente', 'Ferro quente'), ('pasta_caustica', 'Pasta cáustica'), ('outro', 'Outro método')], max_length=30, verbose_name='Método de mochação')),
                ('protocolo_dor_anestesia', models.BooleanField(blank=True, null=True, verbose_name='Anestesia aplicada?')),
                ('protocolo_dor_analgesia', models.BooleanField(blank=True, null=True, verbose_name='Analgesia aplicada?')),
                ('protocolo_dor_sedacao', models.BooleanField(blank=True, null=True, verbose_name='Sedação aplicada?')),
                ('remocao_tetas_realizada', models.BooleanField(blank=True, null=True, verbose_name='Remoção de tetas supranumerárias realizada?')),
                ('protocolo_dor_tetas', models.BooleanField(blank=True, help_text='Anestesia/analgesia para remoção de tetas supranumerárias', null=True, verbose_name='Protocolo de dor para remoção de tetas?')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel_avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela avaliação')),
                ('terneira', models.ForeignKey(limit_choices_to={'categoria': 'terneira', 'sexo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='comportamento_bea', to='animais.animal', verbose_name='Terneira')),
            ],
            options={
                'verbose_name': 'Avaliação de Comportamento BEA',
                'verbose_name_plural': 'Avaliações de Comportamento BEA',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='AmbienteBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('local_paricao', models.CharField(blank=True, choices=[('bercario', 'Berçário'), ('pre_desmame', 'Pré-desmame'), ('maternidade', 'Maternidade'), ('pasto', 'Pasto')], max_length=20, verbose_name='Local de parição')),
                ('tipo_alojamento', models.CharField(blank=True, choices=[('individual', 'Individual'), ('coletivo', 'Coletivo'), ('suspenso', 'Suspenso'), ('chao', 'Chão')], max_length=20, verbose_name='Tipo de alojamento')),
                ('dimensao_baia_m2', models.DecimalField(blank=True, decimal_places=2, help_text='≥3m² para individual, ≥4m²/animal para coletivo', max_digits=5, null=True, verbose_name='Dimensão da baia (m²)')),
                ('numero_animais_baia', models.PositiveIntegerField(blank=True, help_text='Para alojamento coletivo', null=True, verbose_name='Número de animais na baia')),
                ('tipo_cama', models.CharField(blank=True, help_text='Ex: palha, maravalha, areia', max_length=50, verbose_name='Tipo de cama')),
                ('profundidade_cama_cm', models.PositiveIntegerField(blank=True, help_text='Meta: ≥30cm', null=True, verbose_name='Profundidade da cama (cm)')),
                ('score_sujidade', models.CharField(blank=True, choices=[('muito_limpo', 'Muito limpo'), ('limpo', 'Limpo'), ('suja', 'Suja'), ('muito_suja', 'Muito suja')], max_length=20, verbose_name='Score de sujidade da cama')),
                ('tem_aquecimento', models.BooleanField(blank=True, null=True, verbose_name='Tem aquecimento?')),
                ('cortinas_adequadas', models.BooleanField(blank=True, null=True, verbose_name='Cortinas >45cm altura?')),
                ('tem_sombra', models.BooleanField(blank=True, null=True, verbose_name='Tem sombra?')),
                ('tem_ventilacao', models.BooleanField(blank=True, null=True, verbose_name='Tem ventilação/ventiladores?')),
                ('freq_lavagem_mamadeiras', models.CharField(blank=True, choices=[('apos_uso', 'Após cada uso'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('eventual', 'Eventual')], max_length=20, verbose_name='Frequência lavagem mamadeiras')),
                ('freq_lavagem_sondas', models.CharField(blank=True, choices=[('apos_uso', 'Após cada uso'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('eventual', 'Eventual')], max_length=20, verbose_name='Frequência lavagem sondas')),
                ('freq_lavagem_bebedouros', models.CharField(blank=True, choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('eventual', 'Eventual')], max_length=20, verbose_name='Frequência lavagem bebedouros')),
                ('produto_higiene', models.CharField(blank=True, help_text='Nome do produto de limpeza/desinfetante', max_length=100, verbose_name='Produto usado na higiene')),
                ('tem_pop_elaborado', models.BooleanField(blank=True, help_text='Procedimento Operacional Padrão', null=True, verbose_name='POP de higiene elaborado?')),
                ('limpeza_acida_semanal', models.BooleanField(blank=True, null=True, verbose_name='Limpeza ácida semanal?')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel_avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela avaliação')),
                ('terneira', models.ForeignKey(limit_choices_to={'categoria': 'terneira', 'sexo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='ambiente_bea', to='animais.animal', verbose_name='Terneira')),
            ],
            options={
                'verbose_name': 'Avaliação de Ambiente BEA',
                'verbose_name_plural': 'Avaliações de Ambiente BEA',
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
