# Generated by Django 4.2.16 on 2026-08-31 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bem_estar_animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaPresencialBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField(verbose_name='Data da visita')),
                ('observacoes_gerais', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('produtor_visitado', models.ForeignKey(blank=True, limit_choices_to={'perfis__papel': 'produtor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_recebidas_bea', to=settings.AUTH_USER_MODEL, verbose_name='Produtor visitado')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_bea', to='core.propriedade', verbose_name='Propriedade')),
                ('responsavel_tecnico', models.ForeignKey(limit_choices_to={'perfis__papel__in': ['tecnico', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='visitas_realizadas_bea', to=settings.AUTH_USER_MODEL, verbose_name='Responsável técnico')),
            ],
            options={
                'verbose_name': 'Visita Presencial BEA',
                'verbose_name_plural': 'Visitas Presenciais BEA',
                'ordering': ['-data_visita'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciasBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo_evidencia', models.CharField(choices=[('foto', 'Foto'), ('video', 'Vídeo')], max_length=10, verbose_name='Tipo de evidência')),
                ('arquivo', models.FileField(help_text='Fotos: máx 10MB | Vídeos: máx 50MB', upload_to='evidencias_bea/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_bea', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que fez upload')),
            ],
            options={
                'verbose_name': 'Evidência BEA',
                'verbose_name_plural': 'Evidências BEA',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consentimento_dados', models.BooleanField(default=False, verbose_name='Consentimento uso de dados')),
                ('consentimento_imagem', models.BooleanField(default=False, verbose_name='Consentimento uso de imagem')),
                ('data_consentimento', models.DateTimeField(verbose_name='Data do consentimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produtor', models.ForeignKey(limit_choices_to={'perfis__papel': 'produtor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_bea', to=settings.AUTH_USER_MODEL, verbose_name='Produtor')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_bea', to='core.propriedade', verbose_name='Propriedade')),
                ('responsavel_coleta', models.ForeignKey(limit_choices_to={'perfis__papel__in': ['tecnico', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_coletados_bea', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela coleta')),
            ],
            options={
                'verbose_name': 'Consentimento BEA',
                'verbose_name_plural': 'Consentimentos BEA',
                'ordering': ['-data_consentimento'],
                'unique_together': {('propriedade', 'produtor')},
            },
        ),
    ]
