# Generated by Django 4.2.16 on 2026-09-03 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animais', '0001_initial'),
        ('core', '0001_initial'),
        ('bem_estar_animal', '0002_fase4_visitas_consentimento_evidencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaProCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: ProCampo 2026 - Fazenda São José', max_length=200, verbose_name='Nome da jornada')),
                ('data_selecao_produtor', models.DateField(help_text='Limite: 30/08/2026', verbose_name='Data de seleção do produtor')),
                ('data_inicio', models.DateField(verbose_name='Data de início da jornada')),
                ('data_prevista_conclusao', models.DateField(help_text='Após 6 meses do início', verbose_name='Data prevista para conclusão')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejamento', max_length=20, verbose_name='Status')),
                ('minimo_visitas', models.PositiveSmallIntegerField(default=3, verbose_name='Mínimo de visitas')),
                ('baseline_realizado', models.BooleanField(default=False, verbose_name='Baseline realizado?')),
                ('case_sucesso_gerado', models.BooleanField(default=False, verbose_name='Case de sucesso gerado?')),
                ('objetivo_principal', models.TextField(blank=True, verbose_name='Objetivo principal da jornada')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consentimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas', to='bem_estar_animal.consentimentobea', verbose_name='Consentimento associado')),
                ('produtor', models.ForeignKey(limit_choices_to={'perfis__papel': 'produtor'}, on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_produtor', to=settings.AUTH_USER_MODEL, verbose_name='Produtor participante')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_procampo', to='core.propriedade', verbose_name='Propriedade')),
                ('supervisor', models.ForeignKey(limit_choices_to={'perfis__papel__in': ['tecnico', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_supervisionadas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor responsável')),
            ],
            options={
                'verbose_name': 'Jornada ProCampo',
                'verbose_name_plural': 'Jornadas ProCampo',
                'ordering': ['-data_inicio'],
                'unique_together': {('propriedade', 'data_inicio')},
            },
        ),
        migrations.AddField(
            model_name='ambientebea',
            name='fase_alojamento',
            field=models.CharField(blank=True, choices=[('bercario', 'Berçário (0-2 meses)'), ('pre_desmame', 'Pré-desmame (2-6 meses)')], help_text='Separar avaliação por fase de desenvolvimento', max_length=20, verbose_name='Fase de alojamento'),
        ),
        migrations.AddField(
            model_name='ambientebea',
            name='freq_desinfeccao_baias',
            field=models.CharField(blank=True, choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('eventual', 'Eventual')], max_length=20, verbose_name='Frequência desinfecção baias'),
        ),
        migrations.AddField(
            model_name='ambientebea',
            name='freq_lavagem_baldes',
            field=models.CharField(blank=True, choices=[('apos_uso', 'Após cada uso'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('eventual', 'Eventual')], max_length=20, verbose_name='Frequência lavagem baldes'),
        ),
        migrations.AddField(
            model_name='ambientebea',
            name='freq_lavagem_cochos',
            field=models.CharField(blank=True, choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('eventual', 'Eventual')], max_length=20, verbose_name='Frequência lavagem cochos'),
        ),
        migrations.AddField(
            model_name='visitapresencialbea',
            name='acoes_recomendadas',
            field=models.TextField(blank=True, help_text='O que foi recomendado ao produtor', verbose_name='Ações recomendadas'),
        ),
        migrations.AddField(
            model_name='visitapresencialbea',
            name='numero_visita',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1ª, 2ª, 3ª visita...', null=True, verbose_name='Número da visita'),
        ),
        migrations.AddField(
            model_name='visitapresencialbea',
            name='problemas_identificados',
            field=models.TextField(blank=True, help_text='Liste os principais problemas encontrados', verbose_name='Problemas identificados'),
        ),
        migrations.AddField(
            model_name='visitapresencialbea',
            name='tipo_visita',
            field=models.CharField(blank=True, choices=[('baseline', 'Baseline/Diagnóstico Inicial'), ('acompanhamento', 'Acompanhamento'), ('reavaliacao', 'Reavaliação'), ('final', 'Visita Final')], max_length=20, verbose_name='Tipo de visita'),
        ),
        migrations.CreateModel(
            name='PlanoAcaoBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(help_text='Ex: Saúde, Ambiente, Nutrição, Comportamento', max_length=50, verbose_name='Domínio')),
                ('indicador', models.CharField(help_text='Ex: Brix sérico baixo, cama suja', max_length=200, verbose_name='Indicador/Problema')),
                ('situacao_encontrada', models.TextField(help_text='Descreva o problema identificado', verbose_name='Situação encontrada')),
                ('acao_recomendada', models.TextField(help_text='O que deve ser feito para corrigir', verbose_name='Ação recomendada')),
                ('prazo', models.DateField(verbose_name='Prazo para conclusão')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('resultado_obtido', models.TextField(blank=True, help_text='Descreva o que foi realizado e o resultado', verbose_name='Resultado obtido')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_acao', to='bem_estar_animal.jornadaprocampo', verbose_name='Jornada')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela ação')),
                ('visita_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_geradas', to='bem_estar_animal.visitapresencialbea', verbose_name='Visita que gerou a ação')),
            ],
            options={
                'verbose_name': 'Ação do Plano BEA',
                'verbose_name_plural': 'Ações do Plano BEA',
                'ordering': ['prazo', '-prioridade'],
            },
        ),
        migrations.CreateModel(
            name='DietaSolidaBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('inicio_oferta_agua', models.PositiveSmallIntegerField(blank=True, help_text='Recomendado: 1º dia de vida', null=True, verbose_name='Início oferta água (dias de vida)')),
                ('fonte_agua', models.CharField(blank=True, help_text='Ex: Poço, cidade, mina, etc.', max_length=100, verbose_name='Fonte de água')),
                ('tipo_bebedouro', models.CharField(blank=True, choices=[('balde', 'Balde'), ('bebedouro_automatico', 'Bebedouro automático'), ('cocho_agua', 'Cocho de água'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de bebedouro')),
                ('agua_fresca_disponivel', models.BooleanField(blank=True, null=True, verbose_name='Água fresca disponível?')),
                ('inicio_concentrado_dias', models.PositiveSmallIntegerField(blank=True, help_text='Recomendado: 1º dia de vida', null=True, verbose_name='Início concentrado (dias de vida)')),
                ('tipo_racao', models.CharField(blank=True, help_text='Nome comercial ou composição', max_length=100, verbose_name='Tipo de ração/concentrado')),
                ('freq_abastecimento_concentrado', models.CharField(blank=True, choices=[('continuo', 'Contínuo/À vontade'), ('3x_dia', '3x ao dia'), ('2x_dia', '2x ao dia'), ('1x_dia', '1x ao dia'), ('eventual', 'Eventual')], max_length=20, verbose_name='Frequência abastecimento concentrado')),
                ('consumo_concentrado_estimado_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Média por animal', max_digits=5, null=True, verbose_name='Consumo estimado concentrado (kg/dia)')),
                ('inicio_volumoso_dias', models.PositiveSmallIntegerField(blank=True, help_text='Feno ou silagem', null=True, verbose_name='Início volumoso (dias de vida)')),
                ('tipo_volumoso', models.CharField(blank=True, help_text='Ex: Feno coast-cross, silagem milho', max_length=100, verbose_name='Tipo de volumoso')),
                ('freq_abastecimento_volumoso', models.CharField(blank=True, choices=[('continuo', 'Contínuo/À vontade'), ('3x_dia', '3x ao dia'), ('2x_dia', '2x ao dia'), ('1x_dia', '1x ao dia'), ('eventual', 'Eventual')], max_length=20, verbose_name='Frequência abastecimento volumoso')),
                ('consumo_volumoso_estimado_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Média por animal', max_digits=5, null=True, verbose_name='Consumo estimado volumoso (kg/dia)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietas_solidas', to='bem_estar_animal.jornadaprocampo', verbose_name='Jornada ProCampo')),
                ('responsavel_avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela avaliação')),
                ('terneira', models.ForeignKey(limit_choices_to={'categoria__in': ['terneira', 'novilha'], 'sexo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='dieta_solida_bea', to='animais.animal', verbose_name='Terneira')),
            ],
            options={
                'verbose_name': 'Dieta Sólida BEA',
                'verbose_name_plural': 'Dietas Sólidas BEA',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.AddField(
            model_name='visitapresencialbea',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='bem_estar_animal.jornadaprocampo', verbose_name='Jornada ProCampo'),
        ),
    ]
