# Generated by Django 4.2.16 on 2026-09-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_estar_animal', '0003_procampo_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientebea',
            name='treinamento_equipe',
            field=models.BooleanField(blank=True, help_text='Confirma se a equipe foi treinada nos protocolos de limpeza e desinfecção', null=True, verbose_name='Equipe recebeu treinamento de higiene?'),
        ),
    ]
